# Generated by Django 4.1 on 2022-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slotsbooked',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
